String waiverContent(String name) => """
In consideration of the permission to use the roads, trails, and facilities at the Park, I <bold>$name</bold>, the adult participant identified above, freely make the following representations, both for myself, and as parent/legal guardian, on behalf of the above-named minors, if any:


1. I am/We are voluntarily joining and participating in the Activities held inside the Park. For purposes of this Release Agreement, <bold>“Activities”</bold> shall cover any and all activities, events, use of the Park and any of its facilities, its mountain bike trails, roads, and facilities, whether arranged or organized, including but not limited to cycling, jogging, running, training, walking and other activities.

2. I/We shall strictly abide by the rules and regulations imposed by Nature Specialist Inc. and Switchbacks Inc. of which I/we have been made aware, including but not limited to the following: (a) Conditions for Entry and; (b) Mountain Biker’s Code of Responsibility (collectively referred to as <bold>“Guidelines”</bold>). I hereby acknowledge and declare that I/we have completely read and fully understand the Guidelines, copies of which I/we have been provided with. 

3. I am/We are fully aware of the risks associated with participating in the Activities within the Park, which risks include but are not limited to physical or psychological injury, pain, suffering, illness, disfigurement, temporary or permanent disability (including paralysis), economic or emotional loss, and/or death. I/we understand that these injuries or outcomes may arise from my/our own or third party’s actions, inaction, or negligence and even the conditions of the Park which can change due to weather, use and maintenance. Nonetheless, I/we fully assume all risks personally, both known or unknown to me/us, of my participation in the Activities within the Park.

4.  I/we are fully aware of the risks attendant to my/our participation in the Activities within the Park, I/we hereby waive and irrevocably release all rights or claims for damages I/we may have against Nature Specialist Inc. and Switchbacks Inc. their respective parents, subsidiaries, and affiliates, and their respective directors, officers, stockholders, employees, agents, and contractors (the <bold>“Releasees”</bold>), for any illness, injury, damage or loss that I/we and/or my/our properties may sustain during, or as consequence of performing the Activities within the Park or using the Park. Furthermore, I/we hereby irrevocably release and forever discharge and agree to indemnify and hold the Releasees free and harmless from any and all actions for sum of money, accounts, claims, damages and demands whatsoever, or which could have been directly or indirectly adjudged arising out of, connected with, related or incidental to or as a result of my/our participation in the Activities, including any such claims which shall allege negligent acts or omissions on the part of the Releasees, as well as claims, injuries, or damages of any kind or nature asserted against the Releasees by a third party that arise from or relate to my/our participation in the Activities. I/We further warrant and represent that I/we will not institute, and hereby forever waive any legal action, whether civil, criminal or administrative, against the Releasees

5. I/We hereby certify that (a) I/we are physically fit to participate in the Activities and my/our fitness has been certified by a licensed physician; and (b) I/we have the necessary skills, training and experience or knowledge needed to engage in said Activities.

6. <bold>If minor/s are identified above:</bold> I represent and warrant that I am signing this Release Agreement both individually and on behalf of all identified minor/s. I represent and warrant that I am the parent or legal guardian of such minor/s, or otherwise have legal authority to sign this Release Agreement on behalf of the minor/s. I agree to defend, indemnify, and hold Releasees free and harmless from and against any liability, claims, or damages of any kind or nature (including, without limitation, attorney’s fees) asserted against Releasees by or on behalf of any named minor/s where it is alleged that I did not have legal authority to sign this Release Agreement on behalf of the minor/s

<bold>I/We declare that I/we fully understand the terms of this Release Agreement and that I/we have not been influenced by any representations or statements made by or on behalf of the Releasees. I/We further declare that I/we voluntarily and willingly executed this Release Agreement with full knowledge of my/our rights under the law. This Release Agreement shall be binding upon my/our heirs, assigns, successors-in-interest, administrator and legal representatives.</bold>

""";
