// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJ99yQHtRXjWkHAhM1X4Ey9pt8dDl0p8',
    appId: '1:847781439492:android:bdc8767db035a0cbe42d51',
    messagingSenderId: '847781439492',
    projectId: 'timberland-bike-trail',
    storageBucket: 'timberland-bike-trail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSrZPnYzuaHT7ptwMwj4cKXNn_BOmLUpY',
    appId: '1:847781439492:ios:b2a014878f0c7e7ce42d51',
    messagingSenderId: '847781439492',
    projectId: 'timberland-bike-trail',
    storageBucket: 'timberland-bike-trail.appspot.com',
    androidClientId: '847781439492-d8n6n08hiq4ritrvi49daohbdmml92rg.apps.googleusercontent.com',
    iosClientId: '847781439492-q7090g56ic3n2bv8065mjlkmbhp73vpn.apps.googleusercontent.com',
    iosBundleId: 'com.timberland.timberlandMobile',
  );
}
