// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxpOjCy4PaIlpQKEqtbtcIMyfRnfV6njM',
    appId: '1:887706029319:web:e3bfbbd0f9395c788549a2',
    messagingSenderId: '887706029319',
    projectId: 'timberland-ea38a',
    authDomain: 'timberland-ea38a.firebaseapp.com',
    storageBucket: 'timberland-ea38a.appspot.com',
    measurementId: 'G-5JFPNGHDBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzY1CdsTYU4mzCbHGpIF45SXmWzkCzaYQ',
    appId: '1:887706029319:android:f369ae0be48585068549a2',
    messagingSenderId: '887706029319',
    projectId: 'timberland-ea38a',
    storageBucket: 'timberland-ea38a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4L7DrI0zpk40w_x2potlwziIZkMLcBCo',
    appId: '1:887706029319:ios:34c351ef994782bd8549a2',
    messagingSenderId: '887706029319',
    projectId: 'timberland-ea38a',
    storageBucket: 'timberland-ea38a.appspot.com',
    iosBundleId: 'com.example.timberlandManagementFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4L7DrI0zpk40w_x2potlwziIZkMLcBCo',
    appId: '1:887706029319:ios:34c351ef994782bd8549a2',
    messagingSenderId: '887706029319',
    projectId: 'timberland-ea38a',
    storageBucket: 'timberland-ea38a.appspot.com',
    iosBundleId: 'com.example.timberlandManagementFrontend',
  );
}
