const kSubjects = [
  'DIRECTIONS TO TMBP / TIMBERLAND HIGHLANDS RESORT',
  'OPERATING HOURS',
  'RECOMMENDED EQUIPMENT FOR TMBP',
  'RIDER REQUIREMENTS',
  'TRAIL DIFFICULTY RATINGS',
  'SCHEDULING A RIDE',
  'CANCELLING A RIDE',
  'REFUNDS AND RESCHEDULING RIDES',
  'EMERGENCY SERVICES',
  'RESORT ACCESS',
  'BOOKING A STAY AT THE RESORT'
];
