const trailRules = [
  "Always carry a mobile phone with an ICE (in case of emergency) number installed and make sure it is charged before you leave the house.",
  "Make sure your bike is in perfect running order, and bring a multitool, a spare tube, hydration and a snack.",
  "Avoid riding alone; it’s safer and more fun to ride with your friends.",
  "Stay in control at all times, know your limits and the bikes’. It is your responsibility to avoid crashing into other riders and objects around you.",
  "Be respectful and aware of other riders varying skill levels, relax, and have fun.",
  "Do not stop on the trail. Pull off the trail in a safe place if you need to stop for any reason.",
  "When entering a trail or starting downhill, you must look uphill and give way to other riders coming down the trail.",
  "Respect the trail gradings, read and understand the grading descriptions and the trail difficulty index.",
  "Begin on the easier trails and do not ride trails that are beyond your current level of ability.",
  "Even if you have ridden a trail before, be careful. There are always on-going changes and improvements to the trails and features, so they may have changed since your last visit.",
  "Trail conditions change with the weather; respect the added challenge and risk that the elements, such as wind, rain, and mud, can pose to you. If it is windy, do not attempt jumps; keep both wheels on the ground and stay on the easier trails.",
  "If a rider is hurt, do not move them, notify medical services immediately.",
  "Keep off closed trails and forest areas and obey all signs and warnings.",
  "Stay on marked trails only. Do not cut switchbacks, or modify trails.",
  "Do not push or ride up downhill trails.",
  "Respect the environment; take your litter home with you.",
  "Keep out of the bike park if your ability is impaired through the use of drugs or alcohol.",
  "Be friendly, courteous and respectful to your fellow riders, poor conduct will not be tolerated.",
  "Riders 17 years of age and under must be accompanied by a legal guardian (over 18) at all times",
  "All riders must keep their tags visible at all times.",
  "Please help us maintain the park. If you see a problem on the trails report it to park management.",
  "Know your limits."
];
